### ISSUE TITLE
兼容下python@3.9

### ISSUE THREAD

**Issue by maclechan** [1264204425/PdfReader-LangChian-LLM#1]

**Comment by ZhouhaoJiang** [comment]
一般情况下，Python 3.8 的项目可以在 Python 3.9 上运行，因为 Python 的版本升级通常是向后兼容的

**Comment by maclechan** [comment]
> 一般情况下，Python 3.8 的项目可以在 Python 3.9 上运行，因为 Python 的版本升级通常是向后兼容的

执行 pip install -r requirements.txt 

 Using cached starlette-0.31.0-py3-none-any.whl (69 kB)
ERROR: Could not find a version that satisfies the requirement torch==2.0.1+cu117 (from versions: 1.9.0, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1)
ERROR: No matching distribution found for torch==2.0.1+cu117

**Comment by maclechan** [comment]
> 一般情况下，Python 3.8 的项目可以在 Python 3.9 上运行，因为 Python 的版本升级通常是向后兼容的

执行 pip install -r requirements.txt 

Using cached starlette-0.31.0-py3-none-any.whl (69 kB)
ERROR: Could not find a version that satisfies the requirement torch==2.0.1+cu117 (from versions: 1.9.0, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1)
ERROR: No matching distribution found for torch==2.0.1+cu117

**Comment by maclechan** [comment]
> 一般情况下，Python 3.8 的项目可以在 Python 3.9 上运行，因为 Python 的版本升级通常是向后兼容的


执行 pip install -r requirements.txt

Using cached starlette-0.31.0-py3-none-any.whl (69 kB)
ERROR: Could not find a version that satisfies the requirement torch==2.0.1+cu117 (from versions: 1.9.0, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1)
ERROR: No matching distribution found for torch==2.0.1+cu117

没有使用过python哈，请问下，对pip版本有要求吗。
我是在mac下，python切到3.8，没有使用国内源的情况下。

我将 requirements里的 +cu117 具体去掉后，还会报其他版本不兼容，python这个开发语言有这么离谱的吗。

**Comment by ZhouhaoJiang** [comment]
mac可以使用pip3 install torch torchvision torchaudio 如果运行不了的话 需要把模型加载涉及到cuda部分注释掉  
windows需要去英伟达官网搜索cuda11.7安装
然后windows的话使用pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117
