### ISSUE TITLE
不支持文章摘要啊

### ISSUE THREAD

**Issue by mrkingsun** [1264204425/PdfReader-LangChian-LLM#2]
看了一下api.py，还是先进行检索，再把结果拼接到context。并不能问“这篇文章讲了什么”这种问题吧？

**Comment by ZhouhaoJiang** [comment]
是这样子的，目前并没有找到什么好的方法，api.py本质还是随机提取了文章的内容再交给大模型处理，但是我们正在做一个AI论文的项目，大概思路是提前解析论文的结构（摘要，一级标题，二级标题等等..），再进行摘要，如果有好的思路和想法可以一起交流
<img width="925" alt="image" src="https://github.com/ZhouhaoJiang/PdfReader-LangChian-LLM/assets/79627742/c8e00051-2d98-4fae-a1ca-8d5ba2aba204">

**Comment by mrkingsun** [comment]
> 是这样子的，目前并没有找到什么好的方法，api.py本质还是随机提取了文章的内容再交给大模型处理，但是我们正在做一个AI论文的项目，大概思路是提前解析论文的结构（摘要，一级标题，二级标题等等..），再进行摘要，如果有好的思路和想法可以一起交流 <img alt="image" width="925" src="https://private-user-images.githubusercontent.com/79627742/311617477-c8e00051-2d98-4fae-a1ca-8d5ba2aba204.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNDI2NTUsIm5iZiI6MTcxMDE0MjM1NSwicGF0aCI6Ii83OTYyNzc0Mi8zMTE2MTc0NzctYzhlMDAwNTEtMmQ5OC00ZmFlLWExY2EtOGQ1YmEyYWJhMjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDA3MzIzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1OWVkODNmODI3ZDhmNmRiYmFiNTZjYWY4N2QyMjUwYTllNDM2MDUzNTNiYzQ1MTExMjg0ZjgxNWQwMGZjYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5l8QezxK5KccvNgoq2hq76hq6y3jgpK2nNch5sI4uqg">

如果文章不长的话，为什么不直接把全文丢给LLM？不需要相似度检索步骤了

**Comment by ZhouhaoJiang** [comment]
确实，如果文章不长的话，我们可以提前预处理文章的token总数，进行总结，但是这样的话有几个问题：
1. 如果用户需要多次询问文章细节，不构建向量化数据库的话，每次都要把文章作为prompt发过去消耗大量token。
2. 向量化数据库可以返回出根据问题匹配到的文章部分，对于长文来说我们可以快速定位到相关的位置，但是如果只是全文丢给LLM的话就无法做到

**Comment by mrkingsun** [comment]
是的，就是场景不同，比如“摘要”“总结”还是需要全文交给LLM，而具体的问题点需要检索。
